### ISSUE TITLE
Terraform 0.12 support

### ISSUE THREAD

**Issue by Chupaka** [wgebis/terraform-provider-mailgun#3]
Hello.

As https://github.com/terraform-providers/terraform-provider-mailgun/issues/36 has been archived, opening the issue here.

Our organization just finished migration to v0.12 in our Terraform Enterprise installation, so we are locked to this version at least for some time. Can we use v0.5 in TF 0.12?

What terraform policy was mentioned here: https://github.com/terraform-providers/terraform-provider-mailgun/issues/36#issuecomment-716398621 ?

**Comment by wgebis** [comment]
Hello there!
v0.5 in not compatible with Terraform 0.12, it supports new Terraform SDK. You could use in the meantime v0.4.3 from the old repository. 
Policy which is referring to maintaining terraform providers. Now (from 0.13), every provider is named as `org_name/provider_name` and released under registry.terraform.io. In general provider now are tagged as `official` supported by Hashicorp, `verified` supported by the Partners e.g. DigitalOcean etc, and `community` - here is the Mailgun plugin at the moment. Sadly as far I know Mailgun didn't want to develop the terraform provider, that's why I'm here :) .  
Old repositories for legacy provider binaries should be still available.
Let me know in case of issues with the v0.4.3/v0.5, perhaps I will try to help 👍 .
